### ISSUE TITLE
Idea about linking with Tmorrow.com electricity Grid website

### ISSUE THREAD

**Issue by OnigiriJack** [FraserTooth/japan_grid_carbon_api_website#22]
Hello Fraser, this is Jack from CC15. I am very interested in your application. Currently it is Open Source Time and I came across an [API](https://github.com/tmrowco/electricitymap-contrib) made from developers in Copenhagen. The goal of their project is to track the Carbon footprint of countries across the world. I noticed that they were lacking real [time Japanese consumption ](https://www.electricitymap.org/map). Do you know of any ways to find real time electricity grid data in Japan?

**Comment by FraserTooth** [comment]
Hey @OnigiriJack 👋 
Great question! Yes I'm familiar with that project, it's a great initiative (but their API is not free, hence my separate project 😉 )
Regarding live data, many of the grid companies will have a webpage where they present live demand and solar generation data (e.g. [TEPCOs forecast page](https://www.tepco.co.jp/forecast/)) - I haven't gotten round to making use of this yet, as this information doesn't have a breakdown of generation types (coal, gas, etc.) 
It could be used to make a better predictor of current carbon intensity tho, so I'd like to get round to using it.

The data is probably available from that webpage in a raw format (csv probably) but due to CORS restrictions, it's unlikely you'll be able to pull it into this website directly. (I might be wrong, you're welcome to try)

In which case we'll want to scrape it via the API ([GitHub Project](https://github.com/FraserTooth/japan_grid_carbon_api)) on a regular basis, save it, and create an API endpoint for our website to get the data from. A little 面倒くさい, but it allows us to use the data for the AI predictions too, which is neato.

**Comment by OnigiriJack** [comment]
Thank you for the speedy reply. Is it difficult to calculate the consumption breakdown (coal, gas) or do companies deliberately choose not to display that information?

**Comment by FraserTooth** [comment]
Np. 
The latter, the data you found is indeed the stuff I use for the API at present - but as you notice, Thermal Energy `火力` is the only thing describing fossil fuel use (which is odd, because all the other generation types are there 🤔)
The other sad part of this data is that it only gets updated every month, which means the forward predictions are kinda mad 🔮 

If other data becomes available I'd start using it!
I'm involved with an Energy Tech community ([Green Tech Labs](https://greentechlabs.jp/)) here in Tokyo and some members there suggested that I could use planned shutdown data to figure out what plants *aren't* running....but this is just kind of ridiculous compared with ya'know....TEPCO just...telling us what is running like they do in other countries 😆
