### ISSUE TITLE
Location Based Utility Choice

### ISSUE THREAD

**Issue by FraserTooth** [FraserTooth/japan_grid_carbon_api_website#5]
Currently, the First utility shown defaults to TEPCO (because its the biggest)

We should use [Client Side Geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) to automatically choose which Utility to use.

- https://en.wikipedia.org/wiki/Energy_in_Japan (some Japanese utility information)
- Go by the prefecture as a first call - unless there is a better way
- Still default to TEPCO if no location permission given (or outside of Japan)
- If permission allowed, refresh selection

**Comment by rubenispassionate** [comment]
Try to make the code more flexible

**Comment by maruthimohan** [comment]
Hey @FraserTooth , could I work on it?

**Comment by FraserTooth** [comment]
@maruthimohan Sure, go for it!
Let me know if you have any questions regarding which utility to choose, try and keep it simple to start off with!

**Comment by maruthimohan** [comment]
hey @FraserTooth , I have started looking into this issue. After looking into this, I am thinking of starting to work on this in the following way:

- Store a mapping of each utility to its Geo coordinates (based on the headquarters)
- If the user provides Geolocation access and if the user is inside Japan (I am thinking of using Mapbox API to do reverse geocoding and get the user country), then get coordinates and fetch the nearest utility based on the coordinates rather than getting the Prefecture or Administrative Unit and select that utility
- I am choosing this approach because it feels easier to find the distance between coordinates (Using some third party library or some utility) rather than getting the Prefecture or Region because each Geocoding API is returning a different name or format for the same Region/Administrative Unit.
- If the user does not provide Geolocation access or if the user is outside Japan, default to TEPCO

Let me know what you think about this approach.

**Comment by FraserTooth** [comment]
@maruthimohan that all sounds pretty sensible!
I can imagine an odd scenario where a given location gets the wrong utility, but I reckon this solution should do the trick for the most part. Great idea!
Would be wonderful if you could add a basic test for the system btw!

**Comment by maruthimohan** [comment]
Hey @FraserTooth , I would be working on finishing this task for now. As for the tests, that could be worked upon as a part of another independent task is what I am thinking. Let me know what you feel about that.
